sonar.projectKey=fayrus_registrator
sonar.organization=fayrus

sonar.sources=.
sonar.exclusions=vendor/**,docs/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
