sonar.projectKey=fayrus_registrator
sonar.organization=fayrus

sonar.sources=.
sonar.exclusions=vendor/**,docs/**
sonar.coverage.exclusions=registrator.go,backends/etcd-legacy/etcd.go,internal/bridge/bridge.go
sonar.cpd.exclusions=backends/etcd-legacy/etcd.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
